function volume = getTIV(file)
%GETTIV read file .txt or .mat 
%    
% 
%
% input : cell array
%      file.txt : generated by "job_estimate_tiv_cat12" [^tiv.*txt]
%                 
%               or
%      file.mat : generated by "job_tissue_volume"     [seg8.*mat]
%                
%
% output :
%     volume : vector contains TIV values for each file in the same order as selected 
%

file = cellstr(file);

for nbr = 1:length(file)
    [~, ~, ext] = fileparts(file{nbr});
    
    if strcmp(ext,'.mat')
        
        ff = load(file{nbr});
        try
            volume(nbr,1) = sum(ff.volumes.litres);
        catch ME
            if strcmp(ME.identifier,'MATLAB:nonExistentField')              
                error('TIV not found in file: \n%s\n\nCompute TIV using ''job_tissue_volume''',file{nbr});
            else
                rethrow(ME);
            end
            
        end
    elseif strcmp(ext,'.txt')
      volumes_char  = get_file_content_as_char(file{nbr});
      volumes_cell  = split(volumes_char,' ');
      volume_char   = strip(volumes_cell{1});
      assert(~isempty(volume_char),'The file txt is empty :\n%s',file{nbr});

      volume(nbr,1) = str2num(volume_char);   
    
    else
        error('Unexpected file extension: %s', ext);
    end
end



end
